name: Workflow Test
on: workflow_dispatch

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: bienvenida
        run: echo "Bienvenido"
      - name: adios
        run: echo "adios"
      
